# Generated by Django 5.2.6 on 2026-01-29 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Sarlavha', max_length=255)),
                ('title_uz', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('title_ru', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('title_en', models.CharField(db_index=True, help_text='Sarlavha', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text="Batafsil ma'lumot", null=True)),
                ('description_uz', models.TextField(blank=True, help_text="Batafsil ma'lumot", null=True)),
                ('description_ru', models.TextField(blank=True, help_text="Batafsil ma'lumot", null=True)),
                ('description_en', models.TextField(blank=True, help_text="Batafsil ma'lumot", null=True)),
                ('status', models.BooleanField(default=True, help_text="Aktiv yoki yo'q")),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="E'lon qilingan sana")),
                ('type', models.CharField(choices=[('news', 'Yangilik'), ('announcement', "E'lon")], db_index=True, default='news', help_text='Turini tanlang', max_length=20)),
                ('pages', models.ManyToManyField(blank=True, help_text='Post qaysi sahifalarga tegishli', related_name='posts', to='menus.page')),
            ],
            options={
                'verbose_name': "Post (Yangilik/E'lon)",
                'verbose_name_plural': "Postlar (Yangiliklar va E'lonlar)",
                'db_table': 'posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Rasm', upload_to='post_images/')),
                ('post', models.ForeignKey(help_text='Postga tegishli rasm', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Rasmi',
                'verbose_name_plural': 'Post Rasmlari',
                'db_table': 'post_images',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'type', '-published_date'], name='posts_status_97c274_idx'),
        ),
    ]
