# Generated by Django 5.2.6 on 2026-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('title_uz', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_ru', models.CharField(db_index=True, max_length=200, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('description', models.TextField(blank=True, db_index=True, null=True)),
                ('description_uz', models.TextField(blank=True, db_index=True, null=True)),
                ('description_ru', models.TextField(blank=True, db_index=True, null=True)),
                ('description_en', models.TextField(blank=True, db_index=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('title_uz', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('title_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='collaborations/')),
                ('link', models.URLField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
