# Generated by Django 5.2.6 on 2026-01-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('address_uz', models.TextField()),
                ('address_ru', models.TextField()),
                ('address_en', models.TextField()),
                ('logo', models.FileField(upload_to='company_logos/')),
                ('stat_1', models.CharField(max_length=50)),
                ('stat_2', models.CharField(max_length=50)),
                ('stat_3', models.CharField(max_length=50)),
                ('stat_4', models.CharField(max_length=50)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
